export const DEPARTMENTS = [
  "BSc Computer Science",
  "BSc Biotechnology",
  "BSc Microbiology",
  "BSc Biochemistry",
  "BSc Maths and Physics",
  "BA English",
  "BA Economics",
  "BA West Asia",
  "BCom CA",
  "BCom Cooperation",
  "BBA",
  "BVoc Accounting",
  "BVoc Logistics",
  "BVoc Islamic Finance",
  "MSc Computer Science",
  "MCom Finance",
  "MSc Microbiology",
  "MA English",
  "MA History",
  "MA Economics",
];
